trigger:
- dev
- devops
- staging
- staging-local
- master

pool:
  vmImage: 'ubuntu-18.04'

jobs:
- job: Build
  displayName: Build DAO wheel
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install tools'
  - script: pip install -r requirements.txt
    displayName: 'Install requirements'
  - script: python setup.py bdist_wheel
    displayName: 'Build wheel'
  - publish: $(System.DefaultWorkingDirectory)/dist/
    artifact: dao-wheel
